// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBU0ITv2-yYH-qLXcT7rZXSs6fazPGP4uU',
    appId: '1:535380240245:android:fc025dbf147f83d372d53c',
    messagingSenderId: '535380240245',
    projectId: 'flutter-todolist-1683a',
    storageBucket: 'flutter-todolist-1683a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCweqB4cN_1SLwvdJHW-Ya_sxs_RRooSs8',
    appId: '1:535380240245:ios:bdc870ef03d2584072d53c',
    messagingSenderId: '535380240245',
    projectId: 'flutter-todolist-1683a',
    storageBucket: 'flutter-todolist-1683a.appspot.com',
    iosClientId: '535380240245-mimo922uifhmqjdtp1s19s42nuc1p4vd.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoListLmaTasMas',
  );
}
